### ISSUE TITLE
Is this usable in production?

### ISSUE THREAD

**Issue by godalming123** [CuarzoSoftware/SRM#1]
1. Is this still maintained?
2. There are lots of projects in this group that look like they might use something like this (EG: https://github.com/CuarzoSoftware/Louvre or https://github.com/CuarzoSoftware/Doorman) do they use this, and is it stable enough for them?
   If these projects do use this, please add a note in the readme

**Comment by ehopperdietzel** [comment]
Hey,

I'm currently working on the Louvre project (for creating Wayland compositors), and I'm excited to announce that version 1.0.0 is just around the corner! 😄 It's stable and ready for use. I haven't published it yet because I'm in the final stages of writing the documentation and tutorials.

If you want to give it a try, please clone the source code from the `/devel` branch since the main branch is quite outdated. Here's the Git command for that:

```bash
$ git clone -b devel https://github.com/CuarzoSoftware/Louvre.git
```

To generate the HTML documentation, follow these steps:

```bash
$ cd Louvre/scripts/docs
$ sudo gen_doc.sh
```

Please note that these instructions assume you're using a Debian-based distro. If not, you can manually install Doxygen and uncomment the `apt install ...` line in the `gen_doc.sh` script.

The documentation will be generated in a directory named `louvre_tmp`, and it contains instructions on how to build the library, run examples, explore tutorials, and use the C++ API, among other things.

As for the Doorman project, it's an experimental Qt Wayland greeter for a distro I'm considering developing. I haven't worked on it in a while, but feel free to use either project.

Cheers!
