### ISSUE TITLE
segfault when starting srm-basic

### ISSUE THREAD

**Issue by dranull** [CuarzoSoftware/SRM#11]
[drm_info.log](https://pastebin.com/raw/YtsCHnmQ)
[srm_display_info.log](https://pastebin.com/raw/G7gvepZz)
[srm_basic.log](https://pastebin.com/raw/UG3yCJvd)
[coredumpctl.log](https://pastebin.com/raw/3fqphWwd)

I hope everything you need is in the logs, but ask if you need more information.
I'm using Arch, btw.

**Comment by ehopperdietzel** [comment]
Hello, thank you for sharing this. It appears that the issue occurs in `srmBufferGetTextureID()`. Have you tested if `srm-all-connectors` and `srm-multi-session` are functioning correctly?

There are a few options you could try:

1. Disable GBM with **SRM_FORCE_GL_ALLOCATION**=1
2. Force the use of the legacy DRM API with **SRM_FORCE_LEGACY_API**=1
3. Select a different buffer allocator GPU with **SRM_ALLOCATOR_DEVICE**=/dev/dri/card[N]

Additionally, regarding the `srm_basic.log` file, it seems incomplete. Could you please provide the complete log for further analysis?

**Comment by ehopperdietzel** [comment]
Alright, it seems to be an issue with the Nvidia proprietary driver, as it's failing to create a GBM surface (required when it's the allocator device) and is likely crashing when creating DUMB buffers (when the Intel card is the allocator). 

Currently, SRM doesn't offer a way to blacklist a GPU. As a workaround, you could try disabling the Nvidia driver and using only the Intel one, which should resolve the issue. Alternatively, you could replace the Nvidia driver with nouveau. 

I also have an Intel + Nvidia setup, and the Nvidia card works fine with both proprietary and nouveau drivers. Hence, I suspect it might be a driver configuration issue or bug. Perhaps it requires some backend for GBM or similar.

You might want to try running kmscube or the examples provided [here](https://github.com/dvdhrm/docs/tree/master/drm-howto). If those don't work, then it's definitely a driver bug, otherwise, the issue might lie with SRM.

**Comment by ehopperdietzel** [comment]
Thank you for conducting the testing. In the previous versions, a different approach was attempted where each GPU would render into its own connectors and share buffers through DMA if possible. However, this approach rarely worked despite driver support. In the new version, only one GPU handles rendering (the allocator), and the result is copied to dumb buffers of other GPUs for direct scanning out, or if dumb buffers are not supported, a CPU copy is performed, followed by texture creation and rendering using the other GPU. I suspect the crash may occur during the dumb buffer creation, but I will investigate further.

**Comment by ehopperdietzel** [comment]
Hi, I just released v0.5.6 which I think fixes the issue.
